<?php
/**
 * Report formatting layer for WP Guardrail.
 *
 * Converts normalized report payloads into different output formats:
 *  - Summary text  : short, readable, for clients and project managers.
 *  - Technical text: full detail, for developers and support.
 *  - JSON array    : ready for wp_json_encode() export.
 *  - View data     : structured array consumed by PHP view templates.
 *
 * @package WPGuardrail
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Converts normalized report payloads to output formats.
 */
class WPG_Report_Formatter {

	// =========================================================================
	// Text formats.
	// =========================================================================

	/**
	 * Generate a summary text report (for clients / project managers).
	 *
	 * Short, readable — no raw data dumps or array listings.
	 * Answers: what happened, how serious, what to do next.
	 *
	 * @param array $report Normalized report payload.
	 * @return string Plain text.
	 */
	public static function to_summary_text( array $report ): string {
		$lines = array();

		$title  = $report['title']      ?? 'WP Guardrail Report';
		$status = strtoupper( $report['status'] ?? 'UNKNOWN' );
		$date   = $report['created_at'] ?? '';
		$meta   = $report['meta']       ?? array();

		$lines[] = '=== ' . $title . ' ===';
		$lines[] = 'Status:    ' . $status;
		$lines[] = 'Generated: ' . $date;
		$lines[] = '';

		if ( ! empty( $meta['wp_version'] ) ) {
			$lines[] = 'WordPress: ' . $meta['wp_version'];
		}
		if ( ! empty( $meta['php_version'] ) ) {
			$lines[] = 'PHP:       ' . $meta['php_version'];
		}
		if ( ! empty( $meta['active_theme'] ) ) {
			$lines[] = 'Theme:     ' . $meta['active_theme'];
		}
		$lines[] = '';

		// Issues.
		$issues   = $report['issues'] ?? array();
		$critical = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'critical' ) );
		$warnings = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'warning' ) );

		$lines[] = '--- Issues ---';
		if ( empty( $issues ) ) {
			$lines[] = 'No issues found.';
		} else {
			if ( ! empty( $critical ) ) {
				$lines[] = 'Critical (' . count( $critical ) . '):';
				foreach ( $critical as $issue ) {
					$lines[] = '  ! ' . ( $issue['title'] ?? '' );
				}
			}
			if ( ! empty( $warnings ) ) {
				$lines[] = 'Warnings (' . count( $warnings ) . '):';
				foreach ( $warnings as $issue ) {
					$lines[] = '  ^ ' . ( $issue['title'] ?? '' );
				}
			}
			if ( empty( $critical ) && empty( $warnings ) ) {
				$info = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'info' ) );
				$lines[] = 'Informational (' . count( $info ) . '):';
				foreach ( $info as $issue ) {
					$lines[] = '  - ' . ( $issue['title'] ?? '' );
				}
			}
		}
		$lines[] = '';

		// What to do next.
		$recs = $report['recommendations'] ?? array();
		if ( ! empty( $recs ) ) {
			$lines[] = '--- What To Do Next ---';
			foreach ( $recs as $rec ) {
				$priority = isset( $rec['priority'] ) ? '[' . strtoupper( $rec['priority'] ) . '] ' : '';
				$lines[]  = $priority . ( $rec['title'] ?? '' );
				if ( ! empty( $rec['action'] ) ) {
					$lines[] = '    ' . $rec['action'];
				}
			}
			$lines[] = '';
		}

		$lines[] = '---';
		$lines[] = 'Generated by WP Guardrail. This is a snapshot, not live monitoring.';

		return implode( "\n", $lines );
	}

	/**
	 * Generate a technical text report (for developers / support teams).
	 *
	 * Includes environment details, all issues with descriptions,
	 * all section details, and full recommendations.
	 *
	 * @param array $report Normalized report payload.
	 * @return string Plain text.
	 */
	public static function to_technical_text( array $report ): string {
		$lines = array();

		$title  = $report['title']      ?? 'WP Guardrail Report';
		$status = strtoupper( $report['status'] ?? 'UNKNOWN' );
		$meta   = $report['meta']       ?? array();

		$lines[] = '=== ' . $title . ' [TECHNICAL] ===';
		$lines[] = 'Status:    ' . $status;
		$lines[] = 'ID:        ' . ( $report['id'] ?? '' );
		$lines[] = 'Generated: ' . ( $report['created_at'] ?? '' );
		$lines[] = 'Module:    ' . ( $report['module'] ?? '' );
		$lines[] = 'Mode:      technical';
		$lines[] = '';

		// Environment.
		$lines[] = '--- Environment ---';
		foreach ( $meta as $key => $val ) {
			if ( is_scalar( $val ) ) {
				$lines[] = sprintf( '%-22s %s', sanitize_text_field( (string) $key ) . ':', (string) $val );
			}
		}
		$lines[] = '';

		// All issues with detail.
		$issues  = $report['issues'] ?? array();
		$lines[] = '--- Issues (' . count( $issues ) . ') ---';
		if ( empty( $issues ) ) {
			$lines[] = 'None.';
		} else {
			foreach ( $issues as $issue ) {
				$sev    = strtoupper( $issue['severity'] ?? 'INFO' );
				$title  = $issue['title']  ?? '';
				$detail = $issue['detail'] ?? '';
				$mod    = $issue['module'] ?? '';
				$lines[] = '[' . $sev . '] ' . $title . ( $mod ? ' (' . $mod . ')' : '' );
				if ( $detail ) {
					$lines[] = '      ' . $detail;
				}
			}
		}
		$lines[] = '';

		// Section / module details.
		$sections = $report['sections'] ?? array();
		if ( ! empty( $sections ) ) {
			$lines[] = '--- Module Details ---';
			foreach ( $sections as $section ) {
				$s_title  = $section['title']  ?? 'Section';
				$s_status = strtoupper( $section['status'] ?? 'OK' );
				$lines[]  = '';
				$lines[]  = '[ ' . $s_title . ' — ' . $s_status . ' ]';

				foreach ( $section['summary'] ?? array() as $tile ) {
					$lines[] = '  ' . ( $tile['label'] ?? '' ) . ': ' . ( $tile['value'] ?? '' );
				}

				foreach ( $section['details'] ?? array() as $row ) {
					if ( is_array( $row ) && isset( $row['label'] ) ) {
						$lines[] = '  ' . $row['label'] . ': ' . ( $row['value'] ?? '' );
					} elseif ( is_string( $row ) ) {
						$lines[] = '  ' . $row;
					}
				}
			}
			$lines[] = '';
		}

		// Recommendations.
		$recs    = $report['recommendations'] ?? array();
		$lines[] = '--- Recommendations ---';
		if ( empty( $recs ) ) {
			$lines[] = 'None.';
		} else {
			foreach ( $recs as $rec ) {
				$priority = strtoupper( $rec['priority'] ?? 'LOW' );
				$lines[]  = '[' . $priority . '] ' . ( $rec['title'] ?? '' );
				if ( ! empty( $rec['action'] ) ) {
					$lines[] = '      ' . $rec['action'];
				}
			}
		}
		$lines[] = '';
		$lines[] = '---';
		$lines[] = 'Generated by WP Guardrail ' . WPG_VERSION . '. This is a snapshot, not live monitoring.';

		return implode( "\n", $lines );
	}

	// =========================================================================
	// JSON export.
	// =========================================================================

	/**
	 * Return the report array ready for wp_json_encode().
	 *
	 * No transformation needed — the normalized structure is already JSON-safe.
	 *
	 * @param array $report Normalized report payload.
	 * @return array
	 */
	public static function to_json_array( array $report ): array {
		return $report;
	}

	// =========================================================================
	// View data preparation.
	// =========================================================================

	/**
	 * Prepare a structured data array for PHP view templates.
	 *
	 * Returns a flat, view-friendly array extracted from the report.
	 * Templates receive this instead of the raw report to avoid coupling.
	 *
	 * @param array  $report Normalized report payload.
	 * @param string $mode   'summary' or 'technical'.
	 * @return array
	 */
	public static function prepare_view_data( array $report, string $mode = 'summary' ): array {
		$issues   = $report['issues'] ?? array();
		$critical = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'critical' ) );
		$warnings = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'warning' ) );
		$info     = array_values( array_filter( $issues, fn( $i ) => ( $i['severity'] ?? '' ) === 'info' ) );

		return array(
			'report'          => $report,
			'mode'            => $mode,
			'id'              => $report['id']         ?? '',
			'title'           => $report['title']      ?? '',
			'status'          => $report['status']     ?? 'ok',
			'module'          => $report['module']     ?? '',
			'created_at'      => $report['created_at'] ?? '',
			'meta'            => $report['meta']       ?? array(),
			'summary_tiles'   => $report['summary']    ?? array(),
			'sections'        => $report['sections']   ?? array(),
			'issues'          => $issues,
			'critical_issues' => $critical,
			'warning_issues'  => $warnings,
			'info_issues'     => $info,
			'issue_count'     => count( $issues ),
			'recommendations' => $report['recommendations'] ?? array(),
			'summary_text'    => 'summary'   === $mode ? self::to_summary_text( $report )   : '',
			'technical_text'  => 'technical' === $mode ? self::to_technical_text( $report ) : '',
		);
	}
}
